site_name: Dev-veria

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/antoniosousa
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/antonioufpi/
  # alternate:
  #   - name: English
  #     link: /en/
  #     lang: en

plugins:
  - git-revision-date:
      enabled_if_env: CI
  - search:
      lang:
          - pt
          - en

theme:
  icon:
    logo: ""
  features:
    - navigation.instant
    - navigation.tracking
    #- navigation.tabs
    - navigation.expand
    #- navigation.indexes
    - navigation.top
    - header.autohide
  language: pt
  name: material
  palette:
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Modo Noturno
    - scheme: slate
      primary: black
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Modo Dia

markdown_extensions:
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets